<div align="center">

# **_Olist Revenue Intelligence — Data Understanding_**

### Understanding the relational structure of the Olist e-commerce dataset

</div>

## 1. Project Context

This notebook is the first step of the **Olist Revenue Intelligence project**.

The objective of this notebook is to understand the **structure of the Olist e-commerce dataset** before performing any analytical work.

More specifically, this phase focuses on:

- understanding the relational schema of the dataset
- identifying primary keys and relationships between tables
- determining the analytical grains of the data
- locating where revenue is actually stored in the dataset

This step is essential to ensure that subsequent analyses and business metrics are built on a **correct understanding of the underlying data model**.

## 2. Data Loading

In this section, we load the raw Olist dataset tables into Python using pandas.

The goal is to import all available tables in order to explore their structure and understand the relationships between them.

The dataset contains nine CSV files describing different aspects of the e-commerce platform, including customers, orders, products, payments, reviews, and sellers.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_path = "../data/raw/"

In [3]:
customers = pd.read_csv(data_path + "olist_customers_dataset.csv")
geolocation = pd.read_csv(data_path + "olist_geolocation_dataset.csv")
order_items = pd.read_csv(data_path + "olist_order_items_dataset.csv")
payments = pd.read_csv(data_path + "olist_order_payments_dataset.csv")
reviews = pd.read_csv(data_path + "olist_order_reviews_dataset.csv")
orders = pd.read_csv(data_path + "olist_orders_dataset.csv")
products = pd.read_csv(data_path + "olist_products_dataset.csv")
sellers = pd.read_csv(data_path + "olist_sellers_dataset.csv")
translation = pd.read_csv(data_path + "product_category_name_translation.csv")

In [4]:
tables = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "translation": translation
}

## 3. Schema Inspection

Before performing any analytical work, it is necessary to understand the structure of the dataset.

In this section, we inspect each table to identify:

- number of rows and columns
- available variables
- data types
- potential missing values

This step helps us understand the overall structure of the Olist dataset and identify which tables contain the most relevant information for the analysis.

In [5]:
for name, df in tables.items():
    
    print("="*60)
    print(f"TABLE: {name}")
    print("="*60)
    
    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())
    
    print("\nData types:")
    print(df.dtypes)
    
    print("\nMissing values (%):")
    print((df.isna().mean()*100).round(2).sort_values(ascending=False))
    
    print("\nPreview:")
    display(df.head())

============================================================
TABLE: customers
============================================================
Shape: (99441, 5)

Columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Data types:
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

Missing values (%):
customer_id                 0.0
customer_unique_id          0.0
customer_zip_code_prefix    0.0
customer_city               0.0
customer_state              0.0
dtype: float64

Preview:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

============================================================
TABLE: geolocation
============================================================
Shape: (1000163, 5)

Columns:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

Data types:
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

Missing values (%):
geolocation_zip_code_prefix    0.0
geolocation_lat                0.0
geolocation_lng                0.0
geolocation_city               0.0
geolocation_state              0.0
dtype: float64

Preview:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

============================================================
TABLE: order_items
============================================================
Shape: (112650, 7)

Columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Data types:
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

Missing values (%):
order_id               0.0
order_item_id          0.0
product_id             0.0
seller_id              0.0
shipping_limit_date    0.0
price                  0.0
freight_value          0.0
dtype: float64

Preview:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

============================================================
TABLE: payments
============================================================
Shape: (103886, 5)

Columns:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Data types:
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

Missing values (%):
order_id                0.0
payment_sequential      0.0
payment_type            0.0
payment_installments    0.0
payment_value           0.0
dtype: float64

Preview:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

============================================================
TABLE: reviews
============================================================
Shape: (99224, 7)

Columns:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Data types:
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

Missing values (%):
review_comment_title       88.34
review_comment_message     58.70
review_id                   0.00
review_score                0.00
order_id                    0.00
review_creation_date        0.00
review_answer_timestamp     0.00
dtype: float64

Preview:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

============================================================
TABLE: orders
============================================================
Shape: (99441, 8)

Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Data types:
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

Missing values (%):
order_delivered_customer_date    2.98
order_delivered_carrier_date     1.79
order_approved_at                0.16
order_id                         0.00
order_purchase_timestamp         0.00
order_status                     0.00
customer_id                      0.00
order_estimated_delivery_date    0.00
dtype: float64

Preview:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

============================================================
TABLE: products
============================================================
Shape: (32951, 9)

Columns:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Data types:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Missing values (%):
product_category_name         1.85
product_description_lenght    1.85
product_name_lenght           1.85
product_photos_qty            1.85
product_weight_g              0.01
product_height_cm             0.01
product_length_cm             0.01
product_width_cm              0.01
product_id                    0.00
dtype: float64

Preview:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

============================================================
TABLE: sellers
============================================================
Shape: (3095, 4)

Columns:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Data types:
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

Missing values (%):
seller_id                 0.0
seller_zip_code_prefix    0.0
seller_city               0.0
seller_state              0.0
dtype: float64

Preview:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

============================================================
TABLE: translation
============================================================
Shape: (71, 2)

Columns:
['product_category_name', 'product_category_name_english']

Data types:
product_category_name            str
product_category_name_english    str
dtype: object

Missing values (%):
product_category_name            0.0
product_category_name_english    0.0
dtype: float64

Preview:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

## 4. Key Validation

In this section, we verify whether the columns that appear to be identifiers are actually unique.

This step is essential to:
- identify valid primary keys
- avoid incorrect joins
- understand which tables behave as dimensions and which ones behave as transactional tables

In a relational dataset, assuming uniqueness without checking it can lead to duplicated rows and incorrect business metrics.

In [6]:
key_checks = {
    "customers": ["customer_id", "customer_unique_id"],
    "orders": ["order_id"],
    "products": ["product_id"],
    "sellers": ["seller_id"],
    "translation": ["product_category_name"]
}

for table_name, keys in key_checks.items():
    df = tables[table_name]
    
    print("=" * 60)
    print(f"TABLE: {table_name}")
    print("=" * 60)
    
    for key in keys:
        n_rows = len(df)
        n_unique = df[key].nunique(dropna=False)
        is_unique = n_rows == n_unique
        
        print(f"{key}:")
        print(f"  rows      = {n_rows}")
        print(f"  unique    = {n_unique}")
        print(f"  is_unique = {is_unique}")
        print()

============================================================
TABLE: customers
============================================================
customer_id:
  rows      = 99441
  unique    = 99441
  is_unique = True

customer_unique_id:
  rows      = 99441
  unique    = 96096
  is_unique = False

============================================================
TABLE: orders
============================================================
order_id:
  rows      = 99441
  unique    = 99441
  is_unique = True

============================================================
TABLE: products
============================================================
product_id:
  rows      = 32951
  unique    = 32951
  is_unique = True

============================================================
TABLE: sellers
============================================================
seller_id:
  rows      = 3095
  unique    = 3095
  is_unique = True

============================================================
TABLE: translation
============================================================
product_category_name:
  rows      = 71
  unique    = 71
  is_unique = True

## 5. Relationship and Cardinality Analysis

After validating the primary keys, the next step is to understand the relationships between the tables.

In a relational dataset, different tables may be connected through **one-to-one** or **one-to-many relationships**.

Understanding these cardinalities is essential to avoid incorrect joins that could artificially duplicate rows and distort business metrics.

In this section we analyze how many:

- orders each customer has
- items each order contains
- payments are associated with each order
- reviews exist per order

In [7]:
orders_per_customer = orders.groupby("customer_id")["order_id"].nunique()

print("Orders per customer:")
display(orders_per_customer.describe())

Orders per customer:

count    99441.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
Name: order_id, dtype: float64

In [8]:
items_per_order = order_items.groupby("order_id").size()

print("Items per order:")
display(items_per_order.describe())

Items per order:

count    98666.000000
mean         1.141731
std          0.538452
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         21.000000
dtype: float64

In [9]:
payments_per_order = payments.groupby("order_id").size()

print("Payments per order:")
display(payments_per_order.describe())

Payments per order:

count    99440.000000
mean         1.044710
std          0.381166
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         29.000000
dtype: float64

In [10]:
reviews_per_order = reviews.groupby("order_id").size()

print("Reviews per order:")
display(reviews_per_order.describe())

Reviews per order:

count    98673.000000
mean         1.005584
std          0.075060
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
dtype: float64

In [30]:
print("Unique orders in reviews:", reviews["order_id"].nunique())
print("Total review rows:", len(reviews))
print("Orders with more than one review:", (reviews_per_order > 1).sum())

Unique orders in reviews: 98673
Total review rows: 99224
Orders with more than one review: 547

### Methodological note on reviews

Reviews are linked to `order_id`, which means they belong naturally to the **order level**, not to the item level.

The cardinality check also shows that while most orders have a single review entry, a small number of orders have multiple review rows.

As a result, any downstream integration of customer feedback should be done through an **order-level aggregated review table**, rather than by merging the raw reviews table directly into an item-level fact table.

## 6. Order Lifecycle Exploration

Before building revenue metrics, it is necessary to understand the lifecycle of an order.

Orders can have different statuses such as delivered, shipped, canceled, unavailable, or processing.

Not all of these statuses should be treated as completed business transactions.

In this section, we examine the distribution of order statuses in order to determine which subset of orders should be retained for the revenue analysis.

In [11]:
orders["order_status"].value_counts(dropna=False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [12]:
orders["order_status"].value_counts(normalize=True, dropna=False).round(4)

order_status
delivered      0.9702
shipped        0.0111
canceled       0.0063
unavailable    0.0061
invoiced       0.0032
processing     0.0030
created        0.0001
approved       0.0000
Name: proportion, dtype: float64

In [13]:
order_status_summary = (
    orders["order_status"]
    .value_counts(dropna=False)
    .reset_index()
)

order_status_summary.columns = ["order_status", "n_orders"]
order_status_summary["share"] = (
    order_status_summary["n_orders"] / order_status_summary["n_orders"].sum()
).round(4)

order_status_summary

  order_status  n_orders   share
0    delivered     96478  0.9702
1      shipped      1107  0.0111
2     canceled       625  0.0063
3  unavailable       609  0.0061
4     invoiced       314  0.0032
5   processing       301  0.0030
6      created         5  0.0001
7     approved         2  0.0000

In [14]:
orders_delivered = orders[orders["order_status"] == "delivered"].copy()

In [15]:
print("Total orders:", len(orders))
print("Delivered orders:", len(orders_delivered))
print("Share delivered:", round(len(orders_delivered) / len(orders), 4))

Total orders: 99441
Delivered orders: 96478
Share delivered: 0.9702

## 7. Revenue Source Identification

At this stage, the objective is to identify where revenue is actually stored in the Olist dataset.

There are two main monetary sources in the data:

- `price` and `freight_value` in the `order_items` table
- `payment_value` in the `payments` table

These variables do not belong to the same analytical grain, so they must be analyzed carefully.

The purpose of this section is to:
- identify the relevant monetary columns
- compute their aggregate values
- compare item-level revenue with payment-level revenue
- determine the most appropriate revenue definition for the project

In [16]:
monetary_columns = {
    "order_items": ["price", "freight_value"],
    "payments": ["payment_value"]
}

for table_name, cols in monetary_columns.items():
    print("=" * 60)
    print(f"TABLE: {table_name}")
    print("=" * 60)
    print(tables[table_name][cols].describe())
    print()

============================================================
TABLE: order_items
============================================================
               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

============================================================
TABLE: payments
============================================================
       payment_value
count  103886.000000
mean      154.100380
std       217.494064
min         0.000000
25%        56.790000
50%       100.000000
75%       171.837500
max     13664.080000

In [17]:
delivered_order_ids = set(orders_delivered["order_id"])

In [18]:
order_items_delivered = order_items[
    order_items["order_id"].isin(delivered_order_ids)
].copy()

order_items_delivered["item_revenue"] = order_items_delivered["price"]
order_items_delivered["total_revenue"] = (
    order_items_delivered["price"] + order_items_delivered["freight_value"]
)

print("Delivered order_items revenue summary")
print("Product revenue:", round(order_items_delivered["item_revenue"].sum(), 2))
print("Total revenue (price + freight):", round(order_items_delivered["total_revenue"].sum(), 2))

Delivered order_items revenue summary
Product revenue: 13221498.11
Total revenue (price + freight): 15419773.75

In [19]:
payments_delivered = payments[
    payments["order_id"].isin(delivered_order_ids)
].copy()

print("Delivered payments summary")
print("Payment collected:", round(payments_delivered["payment_value"].sum(), 2))

Delivered payments summary
Payment collected: 15422461.77

In [20]:
product_revenue = order_items_delivered["item_revenue"].sum()
total_revenue = order_items_delivered["total_revenue"].sum()
payment_collected = payments_delivered["payment_value"].sum()

revenue_comparison = pd.DataFrame({
    "metric": [
        "Product revenue",
        "Total revenue (price + freight)",
        "Payment collected"
    ],
    "value": [
        round(product_revenue, 2),
        round(total_revenue, 2),
        round(payment_collected, 2)
    ]
})

revenue_comparison

                            metric        value
0                  Product revenue  13221498.11
1  Total revenue (price + freight)  15419773.75
2                Payment collected  15422461.77

In [21]:
difference = total_revenue - payment_collected
relative_difference = (difference / payment_collected) * 100

print("Difference:", round(difference, 2))
print("Relative difference (%):", round(relative_difference, 4))

Difference: -2688.02
Relative difference (%): -0.0174

### Revenue Definition Decision

The comparison between item-side revenue and payment-side revenue shows that:

- `SUM(price + freight_value)` on delivered orders is very close to `SUM(payment_value)`
- the relative difference is negligible

Therefore, the main revenue definition retained for the project is:

**Revenue = SUM(price + freight_value)**

computed on **delivered orders**, with **order_items** as the main analytical grain.

## 8. Preliminary Business Variables

Before building the analytical dataset, it is useful to create a few core business variables that will support future analyses.

These variables help transform raw transactional fields into more interpretable analytical features.

In this section, we create variables related to:

- revenue
- order timing
- delivery timing
- delivery performance

In [22]:
date_cols = [
    "order_purchase_timestamp",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_cols:
    orders_delivered[col] = pd.to_datetime(orders_delivered[col], errors="coerce")

In [23]:
order_items_delivered["item_revenue"] = order_items_delivered["price"]
order_items_delivered["total_revenue"] = (
    order_items_delivered["price"] + order_items_delivered["freight_value"]
)

In [24]:
orders_delivered["order_month"] = (
    orders_delivered["order_purchase_timestamp"]
    .dt.to_period("M")
    .astype(str)
)

In [25]:
orders_delivered["delivery_lead_time_days"] = (
    orders_delivered["order_delivered_customer_date"]
    - orders_delivered["order_purchase_timestamp"]
).dt.days

In [26]:
orders_delivered["estimated_vs_actual_days"] = (
    orders_delivered["order_delivered_customer_date"]
    - orders_delivered["order_estimated_delivery_date"]
).dt.days

In [27]:
orders_delivered["is_late"] = (
    orders_delivered["estimated_vs_actual_days"] > 0
).astype(int)

### Methodological note on delivery variables

The variables `delivery_lead_time_days`, `estimated_vs_actual_days`, and `is_late` are naturally defined at the **order level**.

They are useful for delivery-risk analysis and later predictive modeling, but they should not be interpreted as pure item-level metrics when the analytical grain shifts to `order_items`.

This distinction will matter in later notebooks when separating:
- item-level revenue structure analysis
- order-level operational execution analysis

In [29]:
orders_delivered[
    [
        "order_id",
        "order_purchase_timestamp",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "order_month",
        "delivery_lead_time_days",
        "estimated_vs_actual_days",
        "is_late"
    ]
].head()

,order_id,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,order_month,delivery_lead_time_days,estimated_vs_actual_days,is_late
0,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18,2017-10,8.0,-8.0,0
1,53cdb2fc8bc7dce0b6741e2150273451,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13,2018-07,13.0,-6.0,0
2,47770eb9100c2d0c44946d9cf07ec65d,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04,2018-08,9.0,-18.0,0
3,949d5b44dbf5de918fe9c16f97b45f8a,2017-11-18 19:28:06,2017-12-02 00:28:42,2017-12-15,2017-11,13.0,-13.0,0
4,ad21c59c0840e6cb83a9ceb5573f8159,2018-02-13 21:18:39,2018-02-16 18:17:02,2018-02-26,2018-02,2.0,-10.0,0

In [ ]:
print("Delivery delay summary:")
display(orders_delivered["delivery_delay_days"].describe())

print("\nEstimated vs actual summary:")
display(orders_delivered["estimated_vs_actual_days"].describe())

print("\nLate delivery rate:")
print(round(orders_delivered["is_late"].mean() * 100, 2), "%")

Delivery delay summary:

count    96470.000000
mean        12.093604
std          9.551380
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_delay_days, dtype: float64

Estimated vs actual summary:

count    96470.000000
mean       -11.875889
std         10.182105
min       -147.000000
25%        -17.000000
50%        -12.000000
75%         -7.000000
max        188.000000
Name: estimated_vs_actual_days, dtype: float64

Late delivery rate:
6.77 %

## 9. Analytical Grain Decision

At this stage, the main methodological choices of the project can be formalized.

Based on the previous exploration, the following decisions are retained:

- the main analytical population will be restricted to **delivered orders**
- the main revenue definition will be **price + freight_value**
- the project will rely on **two complementary analytical layers**

### Item-level analytical layer
A first analytical layer will be built at the `order_items` grain in order to support:
- revenue structure analysis
- category-level analysis
- seller-level analysis
- portfolio analysis

### Order-level analytical layer
A second analytical layer will be built at the `orders` grain in order to support:
- delivery performance indicators
- lateness analysis
- customer feedback analysis through reviews
- future predictive modeling

This distinction is necessary because revenue is naturally decomposed at item level, whereas delivery outcomes and review signals are naturally defined at order level.

### 9.1 Decision Summary

The analytical framework retained for the project is the following:

- **Population:** delivered orders only
- **Revenue definition:** `SUM(price + freight_value)`
- **Main customer identifier:** `customer_unique_id`

Two analytical grains will be used downstream:

- **Item-level fact table:** one row per order item, for revenue and portfolio analysis
- **Order-level fact table:** one row per order, for delivery KPIs, review analysis, and predictive modeling

The main transactional tables are therefore:
- `order_items` for detailed commercial structure
- `orders` as the main order-level reference table

In [31]:
analytical_decisions = pd.DataFrame({
    "decision_area": [
        "Population",
        "Revenue definition",
        "Customer identifier",
        "Item-level analytical layer",
        "Order-level analytical layer",
        "Main transactional table",
        "Order-level reference table"
    ],
    "retained_choice": [
        "Delivered orders only",
        "SUM(price + freight_value)",
        "customer_unique_id",
        "One row per order item (revenue, category, seller, portfolio analysis)",
        "One row per order (delivery KPIs, reviews, predictive modeling)",
        "order_items",
        "orders"
    ]
})

analytical_decisions

,decision_area,retained_choice
0,Population,Delivered orders only
1,Revenue definition,SUM(price + freight_value)
2,Customer identifier,customer_unique_id
3,Item-level analytical layer,"One row per order item (revenue, category, sel..."
4,Order-level analytical layer,"One row per order (delivery KPIs, reviews, pre..."
5,Main transactional table,order_items
6,Order-level reference table,orders

## 10. Notebook Conclusion

This notebook provided a structured understanding of the Olist dataset before downstream analytical work.

The main conclusions are the following:

- the dataset is relational and organized around orders, order items, customers, products, payments, and reviews
- `order_items` is the most relevant transactional table for detailed revenue analysis
- `orders` remains the main order-level reference table
- `customer_unique_id` is the relevant identifier for customer-level analysis
- the main analytical population retained for the project is **delivered orders only**
- the main monetary definition retained is **price + freight_value**
- delivery performance variables and review signals are naturally defined at the **order level**

These conclusions establish the methodological foundation of the project.

The next step is to build:
- an **item-level analytical table** for revenue structure analysis
- an **order-level analytical table** for delivery and customer feedback analysis

### 10.1 Transition to Notebook 2

The purpose of the next notebook will be to transform the raw relational tables into structured analytical datasets.

These datasets will serve as the analytical base for:
- business analysis in Python
- KPI construction in SQL
- dashboard development in Power BI
- later predictive extensions

The target outputs of the next notebook will be:

- a clean **fact_order_items** table at item level for revenue and portfolio analysis
- a clean **fact_orders** table at order level for delivery KPIs, review analysis, and predictive modeling

In [32]:
notebook_1_summary = pd.DataFrame({
    "topic": [
        "Population",
        "Revenue definition",
        "Customer identifier",
        "Item-level output",
        "Order-level output"
    ],
    "decision": [
        "Delivered orders only",
        "SUM(price + freight_value)",
        "customer_unique_id",
        "fact_order_items for revenue and portfolio analysis",
        "fact_orders for delivery KPIs, reviews, and predictive extensions"
    ]
})

notebook_1_summary

                 topic                                           decision
0           Population                              Delivered orders only
1   Revenue definition                         SUM(price + freight_value)
2  Customer identifier                                 customer_unique_id
3    Item-level output  fact_order_items for revenue and portfolio ana...
4   Order-level output  fact_orders for delivery KPIs, reviews, and pr...